# Generated by Django 5.0.6 on 2024-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], max_length=1),
        ),
    ]
