# Generated by Django 5.0.6 on 2024-06-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_task_color_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('view_yourmodel', 'Can view your model')]},
        ),
    ]
