# Generated by Django 5.0.6 on 2024-06-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
