# Generated by Django 5.0.6 on 2024-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='imgcaption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='imgsrc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
