# Generated by Django 5.0.6 on 2024-05-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homecontent_imgcaption_homecontent_imgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='imgcaption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='imgsrc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
