# Generated by Django 5.0.6 on 2024-05-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homecontent_imgcaption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
