# Generated by Django 5.0.6 on 2024-05-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homecontent_created_at_homecontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, default='./assets/img/default.jpg', upload_to='./assets/img/'),
        ),
    ]
