# Generated by Django 5.0.6 on 2024-05-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homecontent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='imgsrc',
        ),
    ]
