# Generated by Django 5.0.6 on 2024-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homecontent_imgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
    ]
